# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/degaswifi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/degaswifi/proprietary/bin/FileMonitorService:system/bin/FileMonitorService \
    vendor/samsung/degaswifi/proprietary/bin/appCoda7542Dec:system/bin/appCoda7542Dec \
    vendor/samsung/degaswifi/proprietary/bin/appCoda7542Enc:system/bin/appCoda7542Enc \
    vendor/samsung/degaswifi/proprietary/bin/atcmdsrv:system/bin/atcmdsrv \
    vendor/samsung/degaswifi/proprietary/bin/close_aud_path_fm.sh:system/bin/close_aud_path_fm.sh \
    vendor/samsung/degaswifi/proprietary/bin/close_aud_path_hifi_headset.sh:system/bin/close_aud_path_hifi_headset.sh \
    vendor/samsung/degaswifi/proprietary/bin/connfwexe:system/bin/connfwexe \
    vendor/samsung/degaswifi/proprietary/bin/cploader:system/bin/cploader \
    vendor/samsung/degaswifi/proprietary/bin/ddexe:system/bin/ddexe \
    vendor/samsung/degaswifi/proprietary/bin/dvfm_control.sh:system/bin/dvfm_control.sh \
    vendor/samsung/degaswifi/proprietary/bin/eeh:system/bin/eeh \
    vendor/samsung/degaswifi/proprietary/bin/emmc_fsck:system/bin/emmc_fsck \
    vendor/samsung/degaswifi/proprietary/bin/exit_composite.sh:system/bin/exit_composite.sh \
    vendor/samsung/degaswifi/proprietary/bin/fsck.exfat:system/bin/fsck.exfat \
    vendor/samsung/degaswifi/proprietary/bin/hw.sh:system/bin/hw.sh \
    vendor/samsung/degaswifi/proprietary/bin/hwacc:system/bin/hwacc \
    vendor/samsung/degaswifi/proprietary/bin/load_prod_8787.sh:system/bin/load_prod_8787.sh \
    vendor/samsung/degaswifi/proprietary/bin/mlanutl:system/bin/mlanutl \
    vendor/samsung/degaswifi/proprietary/bin/mpdc:system/bin/mpdc \
    vendor/samsung/degaswifi/proprietary/bin/mpdc_d:system/bin/mpdc_d \
    vendor/samsung/degaswifi/proprietary/bin/mpdc_svr:system/bin/mpdc_svr \
    vendor/samsung/degaswifi/proprietary/bin/msocket_testport:system/bin/msocket_testport \
    vendor/samsung/degaswifi/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/degaswifi/proprietary/bin/open_aud_path_fm_headset.sh:system/bin/open_aud_path_fm_headset.sh \
    vendor/samsung/degaswifi/proprietary/bin/open_aud_path_fm_speaker.sh:system/bin/open_aud_path_fm_speaker.sh \
    vendor/samsung/degaswifi/proprietary/bin/open_aud_path_hifi_headset.sh:system/bin/open_aud_path_hifi_headset.sh \
    vendor/samsung/degaswifi/proprietary/bin/pppd:system/bin/pppd \
    vendor/samsung/degaswifi/proprietary/bin/rfkill:system/bin/rfkill \
    vendor/samsung/degaswifi/proprietary/bin/run_composite.sh:system/bin/run_composite.sh \
    vendor/samsung/degaswifi/proprietary/bin/sensorservice:system/bin/sensorservice \
    vendor/samsung/degaswifi/proprietary/bin/serial_cfun0:system/bin/serial_cfun0 \
    vendor/samsung/degaswifi/proprietary/bin/serial_client:system/bin/serial_client \
    vendor/samsung/degaswifi/proprietary/bin/smdexe:system/bin/smdexe \
    vendor/samsung/degaswifi/proprietary/bin/ss_conn_daemon:system/bin/ss_conn_daemon \
    vendor/samsung/degaswifi/proprietary/bin/tel_launch.sh:system/bin/tel_launch.sh \
    vendor/samsung/degaswifi/proprietary/bin/tel_launch_no_gui.sh:system/bin/tel_launch_no_gui.sh \
    vendor/samsung/degaswifi/proprietary/bin/unload_8787.sh:system/bin/unload_8787.sh \
    vendor/samsung/degaswifi/proprietary/bin/unload_mpdc.sh:system/bin/unload_mpdc.sh \
    vendor/samsung/degaswifi/proprietary/bin/usr_ctl_codec:system/bin/usr_ctl_codec \
    vendor/samsung/degaswifi/proprietary/bin/vcm:system/bin/vcm \
    vendor/samsung/degaswifi/proprietary/etc/asound.conf:system/etc/asound.conf \
    vendor/samsung/degaswifi/proprietary/etc/audio_basic_element.xml:system/etc/audio_basic_element.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_coeff_config.xml:system/etc/audio_coeff_config.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/samsung/degaswifi/proprietary/etc/audio_gain_config.xml:system/etc/audio_gain_config.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_path_config.xml:system/etc/audio_path_config.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/degaswifi/proprietary/etc/audio_swvol_calibration_def.xml:system/etc/audio_swvol_calibration_def.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_swvol_config.xml:system/etc/audio_swvol_config.xml \
    vendor/samsung/degaswifi/proprietary/etc/audio_swvol_element.xml:system/etc/audio_swvol_element.xml \
    vendor/samsung/degaswifi/proprietary/etc/camera_profiles.xml:system/etc/camera_profiles.xml \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/SDIO8887_SDIO_SDIO.bin:system/etc/firmware/mrvl/SDIO8887_SDIO_SDIO.bin \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/WlanCalData_ext.conf:system/etc/firmware/mrvl/WlanCalData_ext.conf \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/bt_cal_data.conf:system/etc/firmware/mrvl/bt_cal_data.conf \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/bt_init_cfg.conf:system/etc/firmware/mrvl/bt_init_cfg.conf \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/reg_alpha2:system/etc/firmware/mrvl/reg_alpha2 \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/sd8887_uapsta.bin:system/etc/firmware/mrvl/sd8887_uapsta.bin \
    vendor/samsung/degaswifi/proprietary/etc/firmware/mrvl/txpwrlimit_cfg.bin:system/etc/firmware/mrvl/txpwrlimit_cfg.bin \
    vendor/samsung/degaswifi/proprietary/etc/gfx.cfg:system/etc/gfx.cfg \
    vendor/samsung/degaswifi/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/degaswifi/proprietary/etc/imx132_still_tuning.data:system/etc/imx132_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/imx132_video_tuning.data:system/etc/imx132_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/imx135_still_tuning.data:system/etc/imx135_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/imx135_video_tuning.data:system/etc/imx135_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/lsi3h5_still_tuning.data:system/etc/lsi3h5_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/lsi3h5_video_tuning.data:system/etc/lsi3h5_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/lsi3h7_still_tuning.data:system/etc/lsi3h7_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/lsi3h7_video_tuning.data:system/etc/lsi3h7_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    vendor/samsung/degaswifi/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/degaswifi/proprietary/etc/mrvl_agps_default.conf:system/etc/mrvl_agps_default.conf \
    vendor/samsung/degaswifi/proprietary/etc/mrvl_gps_platform.conf:system/etc/mrvl_gps_platform.conf \
    vendor/samsung/degaswifi/proprietary/etc/ov5647_darling_still_tuning.data:system/etc/ov5647_darling_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5647_darling_video_tuning.data:system/etc/ov5647_darling_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5647_qtech_still_tuning.data:system/etc/ov5647_qtech_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5647_qtech_video_tuning.data:system/etc/ov5647_qtech_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5647_sunny_still_tuning.data:system/etc/ov5647_sunny_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5647_sunny_video_tuning.data:system/etc/ov5647_sunny_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5648_sunny_af_still_tuning.data:system/etc/ov5648_sunny_af_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5648_sunny_af_video_tuning.data:system/etc/ov5648_sunny_af_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5648_sunny_ff_still_tuning.data:system/etc/ov5648_sunny_ff_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov5648_sunny_ff_video_tuning.data:system/etc/ov5648_sunny_ff_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov8825_still_tuning.data:system/etc/ov8825_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov8825_video_tuning.data:system/etc/ov8825_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov8835_still_tuning.data:system/etc/ov8835_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov8835_video_tuning.data:system/etc/ov8835_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov8850_still_tuning.data:system/etc/ov8850_still_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/ov8850_video_tuning.data:system/etc/ov8850_video_tuning.data \
    vendor/samsung/degaswifi/proprietary/etc/powerdaemon.xml:system/etc/powerdaemon.xml \
    vendor/samsung/degaswifi/proprietary/etc/pxa_testcfg.ini:system/etc/pxa_testcfg.ini \
    vendor/samsung/degaswifi/proprietary/etc/rom.bin:system/etc/rom.bin \
    vendor/samsung/degaswifi/proprietary/etc/sensor_config.xml:system/etc/sensor_config.xml \
    vendor/samsung/degaswifi/proprietary/lib/egl/libEGL_MRVL.so:system/lib/egl/libEGL_MRVL.so \
    vendor/samsung/degaswifi/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/degaswifi/proprietary/lib/egl/libGLESv1_CM_MRVL.so:system/lib/egl/libGLESv1_CM_MRVL.so \
    vendor/samsung/degaswifi/proprietary/lib/egl/libGLESv2_MRVL.so:system/lib/egl/libGLESv2_MRVL.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio.primary.mrvl.so:system/lib/hw/audio.primary.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.adda.mrvl.so:system/lib/hw/audio_path.adda.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.fm.mrvl.so:system/lib/hw/audio_path.fm.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.hifi.mrvl.so:system/lib/hw/audio_path.hifi.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.vc.mrvl.so:system/lib/hw/audio_path.vc.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.voip.mrvl.so:system/lib/hw/audio_path.voip.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_path.vt.mrvl.so:system/lib/hw/audio_path.vt.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/audio_policy.mrvl.so:system/lib/hw/audio_policy.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/camera.mrvl.so:system/lib/hw/camera.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/consumerir.mrvl.so:system/lib/hw/consumerir.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/gralloc.mrvl.so:system/lib/hw/gralloc.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/hwcomposer.mrvl.so:system/lib/hw/hwcomposer.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/power.mrvl.so:system/lib/hw/power.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/hw/sensors.mrvl.so:system/lib/hw/sensors.mrvl.so \
    vendor/samsung/degaswifi/proprietary/lib/libGAL.so:system/lib/libGAL.so \
    vendor/samsung/degaswifi/proprietary/lib/libGLESv2SC.so:system/lib/libGLESv2SC.so \
    vendor/samsung/degaswifi/proprietary/lib/libHWComposerGC.so:system/lib/libHWComposerGC.so \
    vendor/samsung/degaswifi/proprietary/lib/libMarvellWireless.so:system/lib/libMarvellWireless.so \
    vendor/samsung/degaswifi/proprietary/lib/libMrvlOmx.so:system/lib/libMrvlOmx.so \
    vendor/samsung/degaswifi/proprietary/lib/libacoustic.so:system/lib/libacoustic.so \
    vendor/samsung/degaswifi/proprietary/lib/libagps_hal.so:system/lib/libagps_hal.so \
    vendor/samsung/degaswifi/proprietary/lib/libcameraengine.so:system/lib/libcameraengine.so \
    vendor/samsung/degaswifi/proprietary/lib/libgcu.so:system/lib/libgcu.so \
    vendor/samsung/degaswifi/proprietary/lib/libgpucsc.so:system/lib/libgpucsc.so \
    vendor/samsung/degaswifi/proprietary/lib/libgputex.so:system/lib/libgputex.so \
    vendor/samsung/degaswifi/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/degaswifi/proprietary/lib/libionhelper.so:system/lib/libionhelper.so \
    vendor/samsung/degaswifi/proprietary/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \
    vendor/samsung/degaswifi/proprietary/lib/libphycontmem.so:system/lib/libphycontmem.so \
    vendor/samsung/degaswifi/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/degaswifi/proprietary/lib/libseccamera_jni.so:system/lib/libseccamera_jni.so \
    vendor/samsung/degaswifi/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/degaswifi/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/degaswifi/proprietary/lib/libsoundpool.so:system/lib/libsoundpool.so \
    vendor/samsung/degaswifi/proprietary/lib/libsoundspeed.so:system/lib/libsoundspeed.so \
    vendor/samsung/degaswifi/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/degaswifi/proprietary/usr/idc/Synaptics_HID_TouchPad.idc:system/usr/idc/Synaptics_HID_TouchPad.idc \
    vendor/samsung/degaswifi/proprietary/usr/idc/elan-ts.idc:system/usr/idc/elan-ts.idc \
    vendor/samsung/degaswifi/proprietary/usr/idc/ft5306-ts.idc:system/usr/idc/ft5306-ts.idc \
    vendor/samsung/degaswifi/proprietary/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    vendor/samsung/degaswifi/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/samsung/degaswifi/proprietary/vendor/lib/hw/lights.mrvl.so:system/vendor/lib/hw/lights.mrvl.so \
    vendor/samsung/degaswifi/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/degaswifi/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/degaswifi/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/degaswifi/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/degaswifi/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/samsung/degaswifi/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd
